config/routes.rb
Rails.application.routes.draw do

  get 'summary' => "summary#index"

  resource :profile

  resources :exercises

  resources :workouts do 
    resources :tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "workouts#index"

end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile.attributes = profile_params
    @profile.avatar = params[:profile][:avatar]

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:location, :gender, :email, :date_of_birth, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_field :date_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', profile_path %> 

app/views/profiles/index.html.erb
<h1>My Profile</h1>

        <p>Picture:<img src="<%= @profile.profile_image_url %>" class="img-circle"></p>
        <p><span class="glyphicon glyphicon-globe"></span>Location:<%= @profile.location %></p>
        <p><span class="glyphicon glyphicon-user"></span>Gender:<%= @profile.gender %></p>
        <p><span class="glyphicon glyphicon-envelope"></span>Email:<%= @profile.email %></p>
        <p>Date of Birth:<%= @profile.date_of_birth %></p>
        <p><%= link_to 'Show Profile', @profile %></p>
        <p><%= link_to 'Create Profile', edit_profile_path(@profile) %></p>
        <p><%= link_to 'Delete Profile', @profile, method: :delete, data: { confirm: 'Are you sure?' } %></p>
   

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<h1>My Profile</h1>
Name: <%= @profile.user.name %>
        <p>Picture:<img src="<%= @profile.avatar.url(:medium) %>" class="img-rounded"></p>
        <p><span class="glyphicon glyphicon-globe"></span>Location:<%= @profile.location %></p>
        <p><span class="glyphicon glyphicon-user"></span>Gender:<%= @profile.gender %></p>
        <p><span class="glyphicon glyphicon-envelope"></span>Email:<%= @profile.email %></p>
        <p>Date of Birth:<%= @profile.date_of_birth %></p>
        <p><%= link_to 'Show Profile', @profile %></p>
        <p><%= link_to 'Edit Profile', edit_profile_path %></p>
        <p><%= link_to 'Delete Profile', @profile, method: :delete, data: { confirm: 'Are you sure?' } %></p>
   