config/routes.rb
Rails.application.routes.draw do

  get 'summary' => "summary#index"

  resource :profile

  resources :exercises

  resources :workouts do 
    resources :tasks
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "workouts#index"

end

app/models/workout.rb
class Workout < ActiveRecord::Base
	
	belongs_to :user
	has_many :tasks
	has_many :exercises, through: :tasks
	
	
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  # GET /workouts.json
  def index
    if params[:user]
      @person = User.find_by(id: params[:user][:user_id])
      if @person
        @workouts = @person.workouts
      else
        @workouts = current_user.workouts
      end
    else
      @person = current_user
      @workouts = current_user.workouts
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = current_user.workouts.build(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:completed_at, :title, :description, :user_id)
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %> 
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :completed_at %><br>
    <%= f.date_select :completed_at %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
 
  <div class="actions">
    <%= f.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h3>
  Showing <%= link_to @person.name, profile_path(@person.id) %>'s Workouts
</h3>

<%= form_tag "/workouts", method: :get do %>
  <%= collection_select(:user, :user_id, User.all, :id, :name) %>
  <%= submit_tag "Find" %>
<% end %>

<h1>Listing workouts</h1>

<table class='table table-condensed'>
  <thead>
    <tr>
      <th>Completed on</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.completed_at %></td>
        <td><%= workout.title %></td>
        <td><%= workout.description %></td>
        <td><%= link_to 'See Workout', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Completed on</strong>
  <%= @workout.completed_at %>
</p>

<p>
  <strong>Title</strong>
  <%= @workout.title %>
</p>

<p>
  <strong>Workout Notes</strong>
  <%= @workout.description %>
</p>


<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>
<%= link_to 'Add Exercise', new_workout_task_path(@workout) %>

<h1>Exercise List</h1>

<table class="table">
<tr>
	<th>Exercise</th>
	<th>Quantity</th>
	<th>Unit</th>

</tr>
	<%= render @workout.tasks %>
</table>